DROP TABLE IF EXISTS likes;
DROP TABLE IF EXISTS friends;
DROP TABLE IF EXISTS filmsgenres;
DROP TABLE IF EXISTS films;
DROP TABLE IF EXISTS MpaRatings;
DROP TABLE IF EXISTS genres;
DROP TABLE IF EXISTS users;

CREATE TABLE IF NOT EXISTS users (
    user_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR NOT NULL,
    login VARCHAR NOT NULL,
    email VARCHAR NOT NULL,
    birthdate DATE
);

CREATE TABLE IF NOT EXISTS MpaRatings (
    mpa_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR NOT NULL
);

CREATE TABLE IF NOT EXISTS films (
    film_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR NOT NULL,
    description VARCHAR,
    release_date DATE,
    duration INTEGER,
    mpa_id INTEGER REFERENCES MpaRatings(mpa_id)
);

CREATE TABLE IF NOT EXISTS genres (
    genre_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR NOT NULL
);

CREATE TABLE IF NOT EXISTS likes (
    film_id INTEGER REFERENCES Films(film_id),
    user_id INTEGER REFERENCES Users(user_id),
    PRIMARY KEY (film_id, user_id)
);

CREATE TABLE IF NOT EXISTS friends (
    user_id INTEGER REFERENCES Users(user_id),
    friend_id INTEGER REFERENCES Users(user_id),
    PRIMARY KEY (user_id, friend_id)
);

CREATE TABLE IF NOT EXISTS filmsgenres (
    film_id INTEGER REFERENCES Films(film_id),
    genre_id INTEGER REFERENCES Genres(genre_id),
    PRIMARY KEY (film_id, genre_id)
);